# Configuration file for example.launch.py
# Defines parameters for launching 0 to many (here only 1 is enabled)
# Franka Robotics components in
# namespaced or non-namespaced environments.
#
# Note: This is a launch configuration file, not a node parameter file (see: controllers.yaml).
# Ensure all boolean values are quoted ("true" or "false") to avoid YAML parsing issues.
# Not all parameters are currently used but are included for future compatibility.
# Ensure each robot has a unique namespace to prevent topic conflicts.

ROBOT1: # Arbitrary identifier for the first robot (a Mnemonic) 
  arm_id: "fr3" # Reserved for future use, unique arm (i.e. robot model) identifier
  arm_prefix: "left" # Reserved for future use (e.g., robot unique prefix)
  fake_sensor_commands: "false" # Enable fake sensor commands for simulation
  joint_state_rate: 30 # Publishing rate for joint states (Hz)
  load_gripper: "true" # Enable Franka Gripper ("true" or "false")
  namespace: "NS1" # Namespace for robot, any string (empty string allowed - meaningful names recommended)
  robot_ip: "dont-care" # Robotâ€™s IP address or hostname
  urdf_file: "left_no_gz.urdf" # Relative path to URDF in franka_description/robots
  use_fake_hardware: "true" # Use simulated hardware ("true" or "false")
  use_rviz: "true" # Launch RViz if "true" (single instance for all namespaces)
# Uncomment the following lines to add more robots in Namespaces
ROBOT2:
  arm_id: "fr3"
  arm_prefix: "right"
  fake_sensor_commands: "false"
  joint_state_rate: 30 
  load_gripper: "true"
  namespace: "NS2"
  robot_ip: "172.16.0.4"
  urdf_file: "right_no_gz.urdf"
  use_fake_hardware: "true"
  use_rviz: "true" 
# ROBOT3:
#   arm_id: ""
#   arm_prefix: ""
#   fake_sensor_commands: "false"
#   joint_state_rate: 30
#   load_gripper: "false"
#   namespace: "NS_3"
#   robot_ip: "172.16.0.5"
#   urdf_file: "fr3/fr3.urdf.xacro"
#   use_fake_hardware: "false"
#   use_rviz: "false"  

